services:
  ingestion:
    build:
      context: .
      dockerfile: docker/ingestion/Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command:
      [
        "python",
        "-m",
        "src.ingestion.run_ingestion",
        "--source",
        "remoteok"
      ]

  airflow-db:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: skillpulse-airflow:2.10.5
    depends_on:
      airflow-db:
        condition: service_healthy
    environment: &airflow-common-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      PYTHONPATH: /opt/airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "false"
    volumes: &airflow-common-volumes
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./config:/opt/airflow/config
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/project_logs
    command: version

  airflow-webserver:
    image: skillpulse-airflow:2.10.5
    depends_on:
      airflow-db:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow-common-env
    volumes: *airflow-common-volumes
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: skillpulse-airflow:2.10.5
    depends_on:
      airflow-db:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow-common-env
    volumes: *airflow-common-volumes
    command: scheduler

  skillpulse-postgres:
    image: postgres:16
    container_name: skillpulse-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  airflow_postgres_data:
  postgres_data:
